<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQdVtHih\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQdVtHih/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQdVtHih.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQdVtHih\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQdVtHih\App_KernelDevDebugContainer([
    'container.build_hash' => 'QdVtHih',
    'container.build_id' => 'b6c48e01',
    'container.build_time' => 1618738793,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQdVtHih');
