<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'projet_accueil' => [[], ['_controller' => 'App\\Controller\\ProjetController::accueilAction'], [], [['text', '/projet/']], [], []],
    'projet_connexion' => [[], ['_controller' => 'App\\Controller\\ProjetController::connexionAction'], [], [['text', '/projet/connexion']], [], []],
    'projet_creation_compte' => [[], ['_controller' => 'App\\Controller\\ProjetController::creationCompteAction'], [], [['text', '/projet/creationCompte']], [], []],
    'projet_deconnexion' => [[], ['_controller' => 'App\\Controller\\ProjetController::deconnexionAction'], [], [['text', '/projet/deconnexion']], [], []],
    'projet_modification_compte' => [[], ['_controller' => 'App\\Controller\\ProjetController::modificationCompteAction'], [], [['text', '/projet/modifiercompte']], [], []],
    'projet_produits_afficher' => [[], ['_controller' => 'App\\Controller\\ProjetController::produitsAfficherAction'], [], [['text', '/projet/produits/afficher']], [], []],
    'projet_ajout_panier' => [[], ['_controller' => 'App\\Controller\\ProjetController::ajoutPanierAction'], [], [['text', '/projet/panier/ajout']], [], []],
    'projet_gestion_panier' => [[], ['_controller' => 'App\\Controller\\ProjetController::gestionPanierAction'], [], [['text', '/projet/panier/gestion']], [], []],
    'projet_suppression_panier' => [['idPanier'], ['_controller' => 'App\\Controller\\ProjetController::suppressionPanierAction'], [], [['variable', '/', '[^/]++', 'idPanier', true], ['text', '/projet/panier/gestion/suppresion']], [], []],
    'projet_vider_panier' => [['idUser'], ['_controller' => 'App\\Controller\\ProjetController::viderpanierAction'], [], [['variable', '/', '[^/]++', 'idUser', true], ['text', '/projet/panier/gestion/vider']], [], []],
    'projet_acheter_panier' => [['idUser'], ['_controller' => 'App\\Controller\\ProjetController::acheterPanierAction'], [], [['variable', '/', '[^/]++', 'idUser', true], ['text', '/projet/panier/acheter']], [], []],
    'projet_user_gestion' => [[], ['_controller' => 'App\\Controller\\ProjetController::userGestionAction'], [], [['text', '/projet/user/gestion']], [], []],
    'projet_produit_ajout' => [[], ['_controller' => 'App\\Controller\\ProjetController::produitAjoutAction'], [], [['text', '/projet/produit/ajout']], [], []],
    'projet_suppression_user' => [['idUser'], ['_controller' => 'App\\Controller\\ProjetController::suppressionUserAction'], [], [['variable', '/', '[^/]++', 'idUser', true], ['text', '/projet/suppresion']], [], []],
];
