<?php

namespace ContainerQdVtHih;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\myService' shared autowired service.
     *
     * @return \App\Service\myService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'myService.php';

        return $container->privates['App\\Service\\myService'] = new \App\Service\myService();
    }
}
